### ISSUE TITLE
not support video codec 0

### ISSUE THREAD

**Issue by ivanjaros** [panda-media/muxer-fmp4#3]
Hi,
I am using https://github.com/nareix/joy4 as RTMP server. I read flv-processed packets from the connection and am writing them into small 2-seconds long mp4 files(each file is one GOP). I NEED fragmented mp4 so I am trying to use this library since it seems to be compatible with what I need. I have created a simple muxer-wrapper but I am stuck at writing the packets. I am getting _not support video codec 0_ error from `FMP4Muxer.AddPacket()`. The thing is that the data in that packet comes from the RTMP connection, already processed by FLV demuxer. The data is of course h264 video and AAC audio so they should be just fine. I have noticed some "hacks", maybe?, there you pad some byte slices with `[]byte{0x17, 0, 0, 0, 0}`. So I am wondering if there is something I can do to make this work?

**Comment by oddengine** [comment]
> Hi,
> I am using https://github.com/nareix/joy4 as RTMP server. I read flv-processed packets from the connection and am writing them into small 2-seconds long mp4 files(each file is one GOP). I NEED fragmented mp4 so I am trying to use this library since it seems to be compatible with what I need. I have created a simple muxer-wrapper but I am stuck at writing the packets. I am getting _not support video codec 0_ error from `FMP4Muxer.AddPacket()`. The thing is that the data in that packet comes from the RTMP connection, already processed by FLV demuxer. The data is of course h264 video and AAC audio so they should be just fine. I have noticed some "hacks", maybe?, there you pad some byte slices with `[]byte{0x17, 0, 0, 0, 0}`. So I am wondering if there is something I can do to make this work?

Hi,

We are refactoring our full-featured media server, and do not keep maintaining this project already. You can find details here:
https://github.com/studease/rtmpmate

It is not an open-sourced project, but sold in license. Please contact us in Skype if you are interested in it, so that we can provide an online experience for you.

Otherwise, we can also provide a lib of fmp4 remuxer, if you insist.

**Comment by ivanjaros** [comment]
ah, ok. thanks for the info.
